rocket_blog/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'blog.views.home', name='home'),
    # url(r'^$', 'blog.views.profile', name='profile'),
    # url(r'^(?P<slug>[\w\-]+)/$', 'blog.views.post'),
    url(r'^profile/(?P<user>.+)/$', 'blog.views.profile', name='Profile'),
    url(r'^presentation/$', 'blog.views.presentation', name='presentation'),
    url(r'^flight/$', 'blog.views.flight', name='flight'),
    url(r'^login/$', 'blog.views.user_login', name='login'),
    url(r'^logout/$', 'blog.views.user_logout', name='logout'),
    url(r'^register/$', 'blog.views.register', name='register'),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models


# User Profile Model
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username


# Blog Post Model
class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=255)
    description = models.CharField(max_length=255)
    content = models.TextField()
    published = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return u'%s' % self.title


# Blog Post Comment Model
class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60)
    body = models.TextField()
    post = models.ForeignKey(Post)

    def __unicode__(self):
        return unicode("%s: %s" % (self.post, self.body[:60]))

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from blog.models import UserProfile



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

blog/views.py
import user
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from blog.forms import UserForm, UserProfileForm
from blog.models import Post



def home(request):
    posts = Post.objects.filter(published=True)
    return render(request, 'home.html', {'posts': posts})


def presentation(request):
    return render(request, 'presentation.html')



def post(request, slug):
    post = Post.objects.filter(slug=slug)
    return render(request, 'post.html', {'post': post})


def flight(request):
    return render(request, 'flight.html')


def register(request):
    context = RequestContext(request)

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True

        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render_to_response(
            'register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            context)


def user_login(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid login details supplied.")

    else:
        return render_to_response('login.html', {}, context)




@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')


@login_required
def profile(request):
    profile = User.objects.get(user=request.user)
    return render(request, "profile.html", {"profile": profile})

blog/templates/fonts.html
{% extends "base.html" %}


{% block fonts %}

    <link href='https://fonts.googleapis.com/css?family=Caesar+Dressing|Cherry+Cream+Soda|Josefin+Sans:100,400|Rokkitt|Graduate|Pacifico|Special+Elite|Playball|Sancreek' rel='stylesheet' type='text/css'>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300' rel='stylesheet' type='text/css'>

{% endblock %}

blog/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}


    {% block content %}


        <!--<div class="col-sm-8 col-sm-offset-2">
            <h1 class="text-center"> Life @ <i class="fa fa-rocket"></i><br> <span id="rocket">Rocket</span><span id="u">U</span></h1>
        </div>-->

        {% for post in posts %}
            <!--<div class="col-sm-8 col-sm-offset-2 well blog-container">
                <div class="post">
                    <h2 class="text-left"><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>

                    <h3 class="text-center">{{post.description}}</h3>

                    <h4 class="text-right">Posted on <span class="label label-primary"><time datetime="{{post.created|date:"c"}}"> {{post.created|date}} </time></span><h4>

                    <p class="lead">{{ post.content }}</p>

                </div>
            </div>-->
        {% endfor %}


    {% endblock %}

blog/templates/login.html
{% extends "base.html" %}
{% load staticfiles %}

    {% block content %}
        <div class="col-sm-4 col-sm-offset-4" id="login-form">
            <h1 class="text-center" id="form-login">Log me in Scotty.</h1>

            <form id="login_form" method="post" action="{% url 'login' %}">
                {% csrf_token %}

                <div class="form-group">
                    <label class="label-control">Username</label>
                    <input type="text" name="username" class="form-control" placeholder="Username" value="" size="50" />
                </div>

                <div class="form-group">
                    <label class="label-control">Password</label>
                    <input type="password" name="password" class="form-control" value="" placeholder="Password" size="50" />
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-default btn-block btn-lg">Login <i class="fa fa-rocket"></i></button>
                </div>
            </form>
        </div>


        <script type="text/javascript">
            $("input").addClass('form-control');
            $("label").addClass('label-control');
            $("input#id_picture").addClass('btn btn-lg btn-info');
        </script>
    {% endblock %}

blog/templates/navbar.html
{% load staticfiles %}

     <nav class="navbar navbar-default navbar-fixed-top" id="navbar-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top"><i class="fa fa-github"></i> northdacoder.com</a>
            </div>

            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="hidden"><a href="#page-top"></a></li>
                    <li class="page-scroll"><a href="#intro" class="navlink">Mission</a></li>
                    <li class="page-scroll"><a href="" class="navlink">Develop</a></li>
                    <li class="page-scroll"><a href="#learn" class="navlink">Learn</a></li>
                    <li class="page-scroll"><a href="#contact" class="navlink">Contact</a></li>
                </ul>
                <ul style="list-style-type: none;">
                    <li class="pull-right">
                        <a id="googleLogin" class="btn btn-lg btn-block btn-success"><i class="fa fa-rocket"></i> Login</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

{##}
{#    <div class="navbar navbar-default navbar-fixed-top" id="navbar-top" role="navigation">#}
{#      <div class="container">#}
{#        <div class="navbar-header">#}
{#          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">#}
{#            <span class="sr-only">Toggle navigation</span>#}
{#            <span class="icon-bar"></span>#}
{#            <span class="icon-bar"></span>#}
{#            <span class="icon-bar"></span>#}
{#          </button>#}
{#          <a class="navbar-brand" href="{% url 'home' %}"><i class="fa fa-rocket"></i> Northdacoder</a>#}
{#        </div>#}
{#        <div class="navbar-collapse collapse">#}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                {% if user.is_authenticated %}#}
{#                    <li><a href="profile/{{ user.username }}">Profile</a></li>#}
{#                    <li><a href="{% url 'home' %}">Let's Build</a></li>#}
{#                    <li><a href="{% url 'home' %}">Alumni</a></li>#}
{#                    <li><a href="{% url 'logout' %}">Logout</a></li>#}
{#                {% else %}#}
{#                    <li><a href="{% url 'register' %}">Register</a></li>#}
{#                    <li><a href="{% url 'login' %}">Login</a></li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </div>#}
{#      </div>#}
{#    </div>#}
{##}
{##}

blog/templates/post.html
  {% extends 'base.html' %}

   {% block content %}
        <div class="col-sm-6 col-sm-offset-3 blog-post">
            <article>
                <header>
                    <h1> {{post.title}} </h1>
                    <p><time datetime="{{post.created|date:"c"}}">{{post.created|date}}</time></p>
                </header>
                <p class="description">
                    {{post.description}}
                </p>
                {{post.content|safe}}
            </article>
        </div>
    {% endblock %}

blog/templates/presentation.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title> | Northdacoder</title>
    <meta name="author" content="Northdacoder LLC">
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="../static/css/zenburn.css">
    <link rel="stylesheet" href="../static/css/reveal.css">
    <link rel="stylesheet" href="../static/css/default.css" id="theme">
    <link rel="stylesheet" href="../static/fonts/fonts.css">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/cartodb.css" />
    <style type="text/css">
        #page-one {margin-top: 250px;}
    </style>
</head>

	<body>
        <div class="reveal">
            <div class="slides">
                <div class="col-sm-6 col-sm-offset-3">
                    <p class="lead-text">Lets build something.</p>
                </div>
                <section id="page-one">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="row">
                                <h3>Learn JavaScript</h3><a href="" class="btn btn-danger btn-lg">Lets go</a>
                            </div>
                            <div class="row">
                                <h3>Learn Jquery</h3>
                                <button class="btn btn-danger btn-lg">Lets go</button>
                            </div>
                            <div class="row">
                                <h3>Learn Python</h3>
                                <button class="btn btn-danger btn-lg">Lets go</button>
                            </div>
                            <div class="row">
                                <h3>Learn Djagno</h3>
                                <button class="btn btn-danger btn-lg">Lets go</button>
                            </div>
                            <div class="row">
                                <h3>Learn Heroku</h3>
                                <button class="btn btn-danger btn-lg">Lets go</button>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <h3>Not Much</h3>
                        </div>
                    </div>
                </section>
                <section>Box 3</section>
                <section data-background="#168eae"r>
                    <section>Vertical Section 1</section>
                    <section>Vertical Section 2</section>
                </section>
            </div>
        </div>
{#		<div id="map"></div>#}
{#		<div id="overImg"></div>#}
{#		<div id="header">#}
{#			<a href="#">50yrs of The Rolling Stones</a>#}
{#			<div class="sharing">#}
{#				<a class='fb' target='_blank' href='http://www.facebook.com/sharer.php?u=http://rollingstones.vizzuality.com&text=Visualizing 50 years of concerts by The Rolling Stones'> </a>#}
{#				<a class='tw' href='https://twitter.com/share?url=http://rollingstones.vizzuality.com&text=Visualizing 50 years of concerts by The Rolling Stones' target='_blank'> </a>#}
{#			</div>#}
{#		</div>#}
{#		<div class="reveal">#}
{##}
{#			<!-- Any section element inside of this container is displayed as a slide -->#}
{#			<div class="slides">#}
{#				<section class="landing">#}
{#					<div class="introText">#}
{#						<h1 class="hugeNumber">50</h1>#}
{#						<h1>Years of concerts of <strong>The Rolling Stones</strong></h1>#}
{#						<h2>An interactive map of their live-show story.</h2>#}
{#					</div>#}
{#					<div class="nextButton"><a href="#" actual-slide="0"> </a></div>#}
{#				</section>#}
{#			</div>#}
{#		</div>#}
{##}
{#		<div id="timeline">#}
{#			<ul></ul>#}
{#		</div>#}
{#		<div id="cursorsThumbnail"></div>#}
{##}
{#		<a id="wikipedia_logo" href="http://en.wikipedia.org/wiki/Rolling_Stones_concerts" target="_blank"></a>#}
{##}
{#		<div id="pointTT">#}
{#			<p class="date">AHAHAH</p>#}
{#			<p class="name">LELELEL</p>#}
{#		</div>#}

		<script src="../static/js/cartodb.js" type="text/javascript"></script>
		<script src="../static/js/browser.js" type="text/javascript"></script>
		<script src="../static/js/lib/head.min.js" type="text/javascript"></script>
		<script src="../static/js/reveal.min.js" type="text/javascript"></script>
		<script src="../static/js/app.js" type="text/javascript"></script>

        <script type="text/javascript">
            Reveal.initialize({

                // Display controls in the bottom right corner
                controls: true,

                // Display a presentation progress bar
                progress: true,

                // Display the page number of the current slide
                slideNumber: false,

                // Push each slide change to the browser history
                history: false,

                // Enable keyboard shortcuts for navigation
                keyboard: true,

                // Enable the slide overview mode
                overview: true,

                // Vertical centering of slides
                center: true,

                // Enables touch navigation on devices with touch input
                touch: true,

                // Loop the presentation
                loop: false,

                // Change the presentation direction to be RTL
                rtl: false,

                // Turns fragments on and off globally
                fragments: true,

                // Flags if the presentation is running in an embedded mode,
                // i.e. contained within a limited portion of the screen
                embedded: false,

                // Number of milliseconds between automatically proceeding to the
                // next slide, disabled when set to 0, this value can be overwritten
                // by using a data-autoslide attribute on your slides
                autoSlide: 0,

                // Stop auto-sliding after user input
                autoSlideStoppable: true,

                // Enable slide navigation via mouse wheel
                mouseWheel: false,

                // Hides the address bar on mobile devices
                hideAddressBar: true,

                // Opens links in an iframe preview overlay
                previewLinks: false,

                // Transition style
                transition: 'default', // default/cube/page/concave/zoom/linear/fade/none

                // Transition speed
                transitionSpeed: 'default', // default/fast/slow

                // Transition style for full page slide backgrounds
                backgroundTransition: 'default', // default/none/slide/concave/convex/zoom

                // Number of slides away from the current that are visible
                viewDistance: 3,

                // Parallax background image
                parallaxBackgroundImage: '', // e.g. "'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'"

                // Parallax background size
                parallaxBackgroundSize: '' // CSS syntax, e.g. "2100px 900px"


            });
        </script>
  </body>
</html>

blog/templates/profile.html
{% extends "base.html" %}

{% block content %}



{% endblock %}

blog/templates/register.html
{% extends "base.html" %}
{% load staticfiles %}

    {% block content %}

            <h1 class="text-center"><i class="fa fa-rocket"></i> Rocketu Blog Registration</h1>

            {% if registered %}

                <div class="col-sm-4 col-sm-offset-4" id="registration-form">
                    <h1 class="text-center" id="form-register">thank you for registering!</h1>
                    <a href="{% url 'home' %}" class="btn btn-success btn-block btn-lg"><i class="fa fa-home"></i> Take me home.</a>
                </div>

            {% else %}

                <div class="col-sm-4 col-sm-offset-4" id="registration-form">
                    <h1 class="text-center" id="form-register">register here!</h1><br>
                    <form id="user_form" role="form" method="post" action="{% url 'register' %}" enctype="multipart/form-data">

                        {% csrf_token %}

                        {% for field in user_form %}
                            <div class="form-group">
                                <label class="label-control">{{ field.label_tag }}</label><br>
                                {{ field }}
                            </div>
                        {% endfor %}



                        {% for field in profile_form %}
                            <div class="form-group">
                                <label class="label-control">{{ field.label_tag }}</label><br>
                                {{ field }}
                            </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-lg btn-block btn-default">Lets write <i class="fa fa-pencil"></i></button>

                    </form>
                </div>


            {% endif %}


        <script type="text/javascript">
            $("input").addClass('form-control');
            $("label").addClass('label-control');
            $("input#id_picture").addClass('btn btn-lg btn-info');
        </script>
    {% endblock %}

blog/templates/startup.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Sample 4</title>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <link rel="shortcut icon" href="../../flat-ui/images/favicon.ico">
        <link rel="stylesheet" href="../../flat-ui/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="../../flat-ui/css/flat-ui.css">
        <!-- Using only with Flat-UI (free)-->
        <link rel="stylesheet" href="../../common-files/css/icon-font.css">
        <!-- end -->
        <link rel="stylesheet" href="css/style.css">
    </head>

    <body>
        <div class="page-wrapper">
            <!-- header-10 -->
            <header class="header-10">
                <div class="container">
                    <div class="navbar col-sm-12" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle"></button>
                            <a class="brand" href="#">Startup</a>
                         </div>
                        <div class="collapse navbar-collapse pull-right">
                            <ul class="nav pull-left">
                                <li class="active"><a href="#">Home</a></li>
                                <li><a href="#">Account</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                            <form class="navbar-form pull-left">
                                <a class="btn btn-info" href="#">Buy Now</a>
                            </form>
                        </div>
                    </div>
                </div>
            </header>
            <section class="header-10-sub v-center bg-midnight-blue">
                <div class="background">
                    &nbsp;
                </div>
                <div>
                    <div class="container">
                        <div class="hero-unit">
                            <h1>Startup Framework is a set of components</h1>
                            <p>
                                We’ve created the product that will help your
                                <br/>
                                startup to look even better.
                            </p>
                        </div>
                    </div>
                </div>
                <a class="control-btn fui-arrow-down" href="#"> </a>
            </section>

            <!-- content-7  -->
            <section class="content-7 v-center">
                <div>

                    <div class="container">
                        <h3>Take a look in our awesome product</h3>

                        <div class="row v-center">
                            <div class="col-sm-3">
                                <div>
                                    Of course we haven’t forgotten about the responsive layout. Create a website with full mobile
                                    support.
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="col-sm-offset-1">
                                    <div class="screen-wrapper">
                                        <div class="screen">
                                            <img src="../../common-files/img/content/screen-popup.png" alt="">
                                            <img src="../../common-files/img/content/screen.png" alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="col-sm-offset-2">
                                    <h6>Responsive Layout</h6>
                                    Of course we haven’t forgotten about the responsive layout. Full mobile support.
                                    <h6>Retina Ready</h6>
                                    Startup Framework works fine on devices supporting Retina Display. Feel the clarity!
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- content-23  -->
            <section class="content-23 v-center bg-midnight-blue custom-bg">
                <div>
                    <div class="container">
                        <div class="hero-unit hero-unit-bordered">
                            <h1>Scenic Nature</h1>
                        </div>
                    </div>
                </div>
                <a class="control-btn fui-arrow-down" href="#"> </a>
            </section>

            <!-- content-8  -->
            <section class="content-8 v-center">
                <div>
                    <div class="container">
                        <img src="../../common-files/img/content/img-1@2x.png" width="397" height="193" alt="">

                        <h3>Take a look to our amazing Kit</h3>

                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <p>We have a great surprise for Designmodo fans – our first free HTML user interface kit.
                                    Flat UI Free is made on the basis of Twitter Bootstrap in a stunning flat-style.
                                </p>
                                <a class="btn btn-large btn-clear" href="#">TRY IT NOW</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- content-23  -->
            <section class="content-23  v-center bg-midnight-blue">
                <div id="bgVideo" class="background"></div>
                <div>
                    <div class="container">
                        <div class="hero-unit">
                            <h1>Find a perfect suit for
                            <br class="hidden-phone">
                            your startup</h1>
                        </div>
                    </div>
                </div>
                <a class="control-btn fui-arrow-down" href="#"> </a>
            </section>

            <!-- content-8  -->
            <section class="content-8 v-center">
                <div>
                    <div class="container">
                        <img width="380" height="187" alt="" src="img/ticket-red@2x.png"/>
                        <h3>Twenty Five Awesome Samples</h3>
                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <p>
                                    The most important part of the Startup Framework is the samples.
                                    The samples form a set of 25 usable pages or you can add new blocks from UI Kit.
                                </p>
                                <a class="btn btn-large btn-clear" href="#">TRY IT NOW</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- content-11  -->
            <section class="content-11">
                <div class="container">
                    <span>You have the design, you have the code</span>
                    <a class="btn btn-large btn-danger" href="#">TRY IT NOW</a>
                </div>
            </section>

            <!-- footer-3 -->
            <footer class="footer-3">
                <div class="container">
                    <div class="row v-center">
                        <div class="col-sm-2">
                            <a class="brand" href="#">Startup</a>
                        </div>
                        <div class="col-sm-7">
                            <div class="additional-links">
                                Be sure to take a look to our <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <h6>New York, NY</h6>
                            <div class="address">
                                62 West 55th Street, Suite 302<br>New York, NY, 10230
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>

        <!-- Placed at the end of the document so the pages load faster -->
        <script src="../../common-files/js/jquery-1.10.2.min.js"></script>
        <script src="../../flat-ui/js/bootstrap.min.js"></script>
        <script src="../../common-files/js/modernizr.custom.js"></script>
        <script src="../../common-files/js/jquery.scrollTo-1.4.3.1-min.js"></script>
        <script src="../../common-files/js/jquery.parallax.min.js"></script>
        <script src="../../common-files/js/startup-kit.js"></script>
        <script src="js/jquery.backgroundvideo.min.js"></script>
        <script src="js/script.js"></script>
    </body>
</html>